### PR TITLE
Make FastMoney.divide by Zero Always throw

### LINKED ISSUE #250: FastMoney.divide by zero behaves differently for boxed and unboxed doubles
FastMoney.divide by zero throws `ArithmeticException` for boxed Doubles but returns MAX_VALUE unboxed doubles.

### PR DESCRIPTION
**Pull request by marschall**
Make FastMoney.divide by Zero Always throw ArithmeticException no
matter whether the value is boxed or not.

Fixes #250

---
This change is [Reviewable](https://reviewable.io/reviews/javamoney/jsr354-ri/251)

### CODE REVIEW

File: moneta-core/src/main/java/org/javamoney/moneta/FastMoney.java [hunk 1]
```diff
@@ -682,6 +682,9 @@ public FastMoney divide(double divisor) {
         if (NumberVerifier.isInfinityAndNotNaN(divisor)) {
             return new FastMoney(0L, getCurrency());
         }
+        if (divisor == 0.0d) {
+            throw new ArithmeticException("Division by zero");
```
Comment (stokito) [inline moneta-core/src/main/java/org/javamoney/moneta/FastMoney.java]: Just to be sure: is the message of the exception is the same as for Double? Because there might be some tests who checks the message
